development:
  api_key: 2132fee34a5ddfe9c905fdcc7ffb065f
  secret_key: d9e0fc56653627cc0f1b190d7346e718
  callback_url: http://127.0.0.1:3000/
  pretty_errors: true
  set_asset_host_to_callback_url: false
  tunnel:
    public_host_username:
    public_host:
    public_port: 4007
    local_port: 3000
    server_alive_interval: 0    


production:
  api_key: 2132fee34a5ddfe9c905fdcc7ffb065f
  secret_key: d9e0fc56653627cc0f1b190d7346e718
  callback_url: http://www.facebook-connect-demo.com
  pretty_errors: true
  set_asset_host_to_callback_url: false
  tunnel:
    public_host_username:
    public_host:
    public_port: 4007
    local_port: 3000
    server_alive_interval: 0    


    